version: '3'

services:
    web:
        container_name: "perseid-nginx"
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./public:/public
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - perseid-network

    php:
        container_name: "perseid-php"
        image: php:fpm
        volumes:
            - ./public:/public
            - ./config:/config
            - ./app:/app
            - ./vendor:/vendor
            - ./php.ini:/php.ini
        networks:
            - perseid-network

    meilisearch:
        container_name: "perseid-meilisearch"
        image: getmeili/meilisearch
        environment:
            MEILI_MASTER_KEY: "1234"
        volumes:
            - ./data/meilisearch/:/meili_data
        networks:
            - perseid-network
        ports:
            -   "7700:7700"

    elasticsearch:
        container_name: "perseid-elasticsearch"
        image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
        environment:
            - "xpack.security.enabled=true"
            - "discovery.type=single-node"
        volumes:
            -   ./data/elasticsearch/:/usr/share/elasticsearch/data
            -   ./config/certs/:/usr/share/elasticsearch/config/certs/
        networks:
            - perseid-network
        ports:
            - "9200:9200"

    kibana:
        container_name: "perseid-kibana"
        image: docker.elastic.co/kibana/kibana:8.3.3
        environment:
            - ELASTICSEARCH_HOSTS=http://perseid-elasticsearch:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=xd0mAevU9uOxljhFgJtw
            - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/http_ca.crt
        volumes:
            - ./config/certs/:/usr/share/kibana/config/certs
            - ./data/elasticsearch/:/usr/share/kibana/data
        networks:
            - perseid-network
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"


networks:
    perseid-network:
        driver: bridge
